import { Action, ClosingCTA, Eyebrow, Photo, SectionIntro } from "@/components/editorial";
import { Mark, ServiceAreaGraphic } from "@/components/graphics";
import { pageMetadata, site } from "@/lib/site";
export const metadata = pageMetadata("The crew & the neighborhood", "An owner-led crew concept, thoughtful work standards, and an illustrative Columbus service area. Created by Adrocity Studios.", "/crew");
export default function Crew() { return <>
  <section className="interior-hero crew-hero page-gutter"><Eyebrow>03 / THE CREW & SERVICE AREA</Eyebrow><div className="interior-hero-grid"><h1>SMALL CREW.<br /><span>LONG MEMORY.</span></h1><div className="hero-side"><p className="large-copy">The kind of company that remembers the house, not just the job number.</p><p>Steady is a fictional owner-led HVAC crew built around a simple idea: the people doing the work should be accountable for explaining it.</p></div></div></section>
  <div className="crew-photo"><Photo priority src="/images/steady-crew.webp" alt="Four fictional HVAC crew members standing beside an unbranded white service van in a residential driveway." captionText="AI-GENERATED FICTIONAL CREW · NOT REAL EMPLOYEES" /></div>
  <section className="crew-model page-gutter section-space" data-reveal><SectionIntro number="01" label="FOUR PEOPLE. ONE WAY OF WORKING." title={<>A name behind<br />every next step.</>} description="This is the team model imagined for Steady. These are illustrative roles, not employee profiles or claims about a real business." /><div className="crew-roles">{[{ role: "THE OWNER / LEAD TECHNICIAN", title: "The buck stops here.", body: "Reviews the difficult calls, explains recommendations, and stays connected to the work instead of disappearing after the quote." }, { role: "TWO FIELD TECHNICIANS", title: "Good work is a shared habit.", body: "Use clear job notes, protect the home, and leave each other enough context to keep the next visit useful." }, { role: "THE COORDINATOR", title: "A handoff with context.", body: "Keeps the homeowner informed about next steps and makes sure their questions travel with the job." }].map(item => <article key={item.role}><span className="eyebrow">{item.role}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
  <section className="crew-manifesto page-gutter section-space" data-reveal><Mark /><blockquote>“If we can’t explain why<br />we’re recommending it,<br /><em>we haven’t finished<br />the job.”</em></blockquote><p>THE STEADY STANDARD · FICTIONAL BRAND PRINCIPLE, NOT A TESTIMONIAL</p></section>
  <section id="service-area" className="crew-area page-gutter section-space" data-reveal><div><Eyebrow>02 / THE NEIGHBORHOOD</Eyebrow><h2>Columbus roots.<br />Nearby routes.</h2><p>The concept imagines a residential crew working in Columbus and the surrounding communities below. A focused area makes room for useful communication and continuity.</p><div className="neighborhood-list">{site.areas.map(area => <span key={area}>{area}<span aria-hidden="true">+</span></span>)}</div><div className="hours-box"><span className="eyebrow">ILLUSTRATIVE OFFICE HOURS</span><p>{site.hours}</p><small>No real appointments, emergency coverage, or dispatch. Area boundaries and availability would be verified for a real business.</small></div><Action href="#request" variant="outline">Explore an inquiry from your area</Action></div><ServiceAreaGraphic /></section>
  <section className="agency-note page-gutter section-space" data-reveal><Eyebrow>03 / BEHIND THE CONCEPT</Eyebrow><div><h2>Imaginary company.<br />Very real craft.</h2><div><p>This website was created by Adrocity Studios to show what a thoughtfully designed small-business website can do: explain the work, make the next step obvious, and give a conversation a better start.</p><p>Every company detail is illustrative. Generated photography is visual direction for a future client shoot, not evidence of real work.</p><Action href={site.agency}>Meet Adrocity Studios</Action></div></div></section>
  <ClosingCTA />
</>; }

