import { Action, ClosingCTA, Eyebrow, Photo, SectionIntro } from "@/components/editorial";
import { AirDial, Arrow } from "@/components/graphics";
import Link from "next/link";
import { pageMetadata } from "@/lib/site";
export const metadata = pageMetadata("New systems, thoughtfully chosen", "What to expect from a home HVAC assessment, system comparison, and planned replacement. Fictional company concept.", "/new-systems");
export default function NewSystems() { return <>
  <section className="interior-hero systems-hero page-gutter"><Eyebrow>02 / REPLACEMENT & INSTALLATION</Eyebrow><div className="systems-hero-grid"><div><h1>THE RIGHT FIT.<br /><span>NOT JUST<br />A NEW BOX.</span></h1></div><div className="systems-hero-aside"><AirDial small /><p>A good system starts with a good understanding of your home.</p><Action href="#request">Request a system assessment</Action><small>Explore the local preview. Nothing is submitted.</small></div></div></section>
  <section className="assessment-intro page-gutter section-space" data-reveal><SectionIntro number="01" label="A DECISION WORTH THINKING THROUGH" title={<>Replace the uncertainty.<br />Then the equipment.</>} /><div><p className="large-copy">Another repair. An uncomfortable room. A system you’re no longer sure about.</p><p>Those are reasons to have a conversation, not automatic reasons to buy. A useful assessment separates the condition of the equipment from the needs of the house.</p><p>Sometimes the right next step is a repair. Sometimes it’s a better plan for replacement. You should understand the reasons either way.</p><Link className="text-link" href="/field-notes/repair-or-replace">Read the repair-or-replace field note <Arrow /></Link></div></section>
  <div className="systems-photo"><Photo src="/images/steady-installation.webp" alt="Illustrative technician reviewing a closed outdoor heat pump beside a residential home." captionText="AI-GENERATED CONCEPT SCENE · NOT A COMPLETED INSTALLATION" /></div>
  <section className="assessment-sheet page-gutter section-space" data-reveal><div className="sheet-header"><Eyebrow>02 / THE HOME, BEFORE THE HARDWARE</Eyebrow><span className="eyebrow">STEADY ASSESSMENT / FIELD GUIDE</span></div><h2>Measure twice.<br />Recommend once.</h2><div className="assessment-grid">{[{ title: "The way the house lives.", body: "Room layout, insulation, windows, sun exposure, and the spaces that are harder to keep comfortable." }, { title: "The system you have.", body: "Equipment condition, repair history, ductwork, electrical requirements, and the setup that’s already in place." }, { title: "The load, not a guess.", body: "A properly scoped load calculation and airflow review inform capacity. Bigger isn’t automatically a better fit." }, { title: "The priorities that matter.", body: "Comfort, noise, upfront budget, operating considerations, and how long you plan to stay in the home." }].map((item, i) => <article key={item.title}><span className="assessment-index">0{i + 1}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
  <section className="options-section page-gutter section-space" data-reveal><SectionIntro number="03" label="OPTIONS, IN PLAIN ENGLISH" title={<>Different ways<br />to feel right.</>} description="The best choice depends on the home. These are starting points for a conversation, not a recommendation for your specific system." /><div className="system-options">{[{ title: "Furnace + central AC", label: "A FAMILIAR PAIRING", body: "Separate heating and cooling equipment using a shared duct system.", consideration: "Consider existing fuel service, duct condition, equipment compatibility, and installation requirements." }, { title: "Heat pump", label: "HEATING & COOLING IN ONE", body: "Moves heat to provide cooling in summer and heating in colder weather.", consideration: "Consider local winter conditions, electrical capacity, equipment selection, and whether backup heat is appropriate." }, { title: "Ductless system", label: "ROOM-BY-ROOM POSSIBILITIES", body: "An option for additions or spaces without suitable existing ductwork.", consideration: "Consider indoor-unit placement, drainage, electrical requirements, and how it works with the rest of the home." }].map((item, i) => <article key={item.title}><span className="eyebrow">0{i + 1} / {item.label}</span><h3>{item.title}</h3><p>{item.body}</p><div><b>Worth discussing</b><p>{item.consideration}</p></div></article>)}</div><p className="small-note">No fixed prices or promised savings. Equipment, access, ductwork, electrical work, permits, and installation scope can all affect the proposal.</p></section>
  <section className="installation-section page-gutter section-space" data-reveal><div><Eyebrow light>04 / THE WORK AROUND THE WORK</Eyebrow><h2>It’s your home.<br />We’d work<br /><em>like it.</em></h2></div><div className="install-steps"><article><span>BEFORE</span><h3>A plan you can follow.</h3><p>Confirm the scope, equipment, access, expected interruptions, and responsibilities. Understand what is included and what could change.</p></article><article><span>DURING</span><h3>Care for the space.</h3><p>Protect walking routes, keep equipment and materials organized, and explain changes before proceeding.</p></article><article><span>AFTER</span><h3>A proper handover.</h3><p>Review the installation checks, controls, maintenance needs, and documentation. Leave time for your questions.</p></article></div></section>
  <ClosingCTA title={<>Your house has a story.<br />Let’s start there.</>} />
</>; }

