export type Article = {
  slug: string; title: string; category: string; readTime: string; intro: string;
  sections: { heading: string; paragraphs: string[]; bullets?: string[] }[];
  takeaway: string; relatedHref: string; relatedLabel: string;
};

export const articles: Article[] = [
  {
    slug: "repair-or-replace",
    title: "Repair or replace? Start with the house.",
    category: "MAKING A DECISION", readTime: "6 MIN READ",
    intro: "A repair bill can make a new system look tempting. A new-system quote can make one more repair look sensible. A useful assessment helps you get beyond those two numbers and understand what you’re actually deciding.",
    sections: [
      { heading: "First, separate the fault from the bigger picture.", paragraphs: ["A failed component and a system that no longer suits the house are different problems. Before talking about replacement, ask the technician to explain what has failed, how they established that, and what a repair would involve. A diagnosis should give you something more concrete than ‘it’s old.’", "Then look at the equipment’s overall condition. A repair can address today’s fault without resolving another concern elsewhere in the system. Ask which findings are confirmed, which need further investigation, and which are simply possibilities. Those distinctions help you make a decision without treating every uncertainty as a reason to buy."] },
      { heading: "Bring the repair history into the conversation.", paragraphs: ["An isolated repair is different from a pattern of recurring faults. If you have service notes or invoices, share them. You do not need to reconstruct every visit; a rough timeline of problems and work already completed is still useful.", "Equipment age belongs in this discussion, but it should not make the decision on its own. Condition, parts availability, the nature of the current fault, and your plans for the home all matter. Ask how confident the technician is that the proposed work addresses the problem you called about."] },
      { heading: "Talk about the rooms, not just the machine.", paragraphs: ["If the upstairs has always been warmer or one room never seems comfortable, mention it before equipment is selected. A new unit connected to the same unresolved airflow problem may not address the thing that bothers you most.", "A well-scoped assessment considers the home’s layout, insulation, windows, exposure, and ductwork. Where replacement is being proposed, ask how the capacity recommendation was determined. Matching the old unit’s size is not the same as confirming what the house needs now."], bullets: ["Which rooms are uncomfortable, and at what time of day?", "Has the house changed through an addition, new windows, or insulation work?", "Is the concern temperature, humidity, noise, reliability, or several of these?", "How does the proposed work address that particular concern?"] },
      { heading: "Compare complete proposals.", paragraphs: ["An equipment model and a single total do not tell the whole story. Ask what is included in removal, installation, electrical work, duct modifications, controls, permits where needed, testing, and cleanup. If an item is excluded or depends on what the crew finds, that should be visible in the proposal.", "Compare the written scope alongside the price. A lower total may describe less work; a higher total should still be explained. Do not assume that a promise of better comfort or lower bills substitutes for a clear description of what will be done. Actual performance depends on equipment selection, installation, the home, and how the system is used."] },
      { heading: "Make room for your own priorities.", paragraphs: ["A homeowner planning to stay for years may weigh the options differently from someone preparing to move. A household with a limited immediate budget may need to understand whether a reasonable repair can buy time. Those are useful constraints, not obstacles to hide from the technician.", "Ask for the practical tradeoffs in plain language. What would repairing now resolve? What would remain uncertain? What would replacement change, and what would it not change? If an efficiency or savings estimate is offered, ask what assumptions it uses rather than treating it as a guaranteed result."] },
      { heading: "Leave with a next step you can explain.", paragraphs: ["You should be able to describe the finding, the available options, and the reason for the recommendation in your own words. If you cannot, ask for another explanation or written notes. A sound recommendation should stand up to a few straightforward questions.", "For a planned replacement, the next step may be a more detailed home assessment rather than an immediate purchase. For a repair, it may be approval of a specific scope and price. Either way, the decision should begin with your home and the evidence in front of you."] },
    ],
    takeaway: "The useful question isn’t simply ‘How old is it?’ It’s ‘What does this option solve for this house, and what remains?’",
    relatedHref: "/new-systems", relatedLabel: "Explore the new-system approach",
  },
  {
    slug: "ac-not-cooling",
    title: "AC not cooling? Here’s what to tell the technician.",
    category: "BEFORE THE FIRST CALL", readTime: "5 MIN READ",
    intro: "You don’t need to diagnose an air conditioner before calling for help. A few ordinary observations can give the technician a much better starting point, without asking you to open equipment or handle anything unsafe.",
    sections: [
      { heading: "Describe what ‘not cooling’ means in your home.", paragraphs: ["The phrase can describe several different experiences. Is the system silent? Is air coming from the vents but feeling warmer than usual? Does cooling begin and then stop? Is the whole house affected, or just a few rooms?", "Use normal language. ‘The fan sounds like it’s running, but the downstairs hasn’t cooled since lunch’ is more useful than a guessed diagnosis. A technician needs the symptom and the pattern; they can investigate the cause."] },
      { heading: "Note when it started and what changed.", paragraphs: ["Think about the last time the home felt normal. Did the change happen suddenly or gradually? Does it happen every afternoon, after the system has been running for a while, or at seemingly random times?", "Mention recent service, thermostat changes, a power interruption, building work, or anything else that coincided with the problem. A coincidence is not proof of a cause, but a timeline helps the technician ask better questions. You do not need to perform tests to create one."], bullets: ["When you first noticed the change.", "Whether the issue is constant or comes and goes.", "Which rooms or floors are affected.", "Any new sounds or visible water noticed from a safe, ordinary location."] },
      { heading: "Share the system type if you already know it.", paragraphs: ["A central AC paired with a furnace, a heat pump, and a ductless unit have different setups. If you know what you have, say so. If you do not, ‘I’m not sure’ is a perfectly useful answer.", "An existing equipment record, an old invoice, or a label you can read without moving or opening anything may help. There is no need to climb, remove a cover, reach behind equipment, or get close to moving parts to identify a model. The technician can confirm details at the visit."] },
      { heading: "Avoid turning observations into risky troubleshooting.", paragraphs: ["This is a call-preparation checklist, not a repair procedure. Do not open electrical panels, handle refrigerant, bypass a control, or try repeated resets. A video that seems to show the same symptom may describe different equipment or a different fault.", "If you smell gas, see smoke, or a carbon monoxide alarm sounds, leave the area and contact the appropriate emergency service from a safe location. An ordinary HVAC inquiry is not the right route for an immediate hazard. If you are unsure whether equipment is safe to approach, keep your distance and seek qualified help."] },
      { heading: "Make the practical details easy to find.", paragraphs: ["A real contractor will need to confirm the service address, coverage area, and a way to reach you. Let them know about access restrictions, a locked gate, pets that need to be secured, or any scheduling constraints. These details help the visit run more smoothly.", "If indoor conditions are affecting someone vulnerable to heat, explain that promptly and seek appropriate assistance rather than relying on an unconfirmed appointment. A form submission alone does not establish availability or guarantee a response time."] },
      { heading: "A useful first message can be short.", paragraphs: ["Here is a fictional example: ‘Our central AC has been blowing air that feels warm since yesterday afternoon. Both floors are affected. We haven’t had recent service, and I don’t know the equipment age. The outdoor unit is accessible from the side gate. Can you confirm whether you serve our area and explain the next step?’", "That message gives the crew a symptom, timeline, scope, and practical context. It does not claim to know what has failed. A diagnosis still needs proper checks, and any proposed repair should come with a clear explanation and approval before work begins."] },
    ],
    takeaway: "Tell the crew what you’ve noticed, not what you think you have to fix. Clear observations are enough to start.",
    relatedHref: "/repairs", relatedLabel: "See how the repair process works",
  },
];
