import Link from "next/link";
import { Action, AreaDetails, ClosingCTA, Eyebrow, Photo, SectionIntro } from "@/components/editorial";
import { AirDial, Arrow, Mark, ServiceAreaGraphic } from "@/components/graphics";
import { pageMetadata, site } from "@/lib/site";
import { articles } from "@/content/articles";
export const metadata = pageMetadata("Good air. Steady hands.", "Residential heating, cooling, and a clearer way forward. A fictional Columbus HVAC concept by Adrocity Studios.", "/");

export default function Home() {
  return <>
    <section className="home-hero page-gutter">
      <div className="hero-kicker"><Eyebrow>HEATING & COOLING / COLUMBUS, OHIO</Eyebrow><span className="hero-coordinate">RESIDENTIAL. THROUGH AND THROUGH.</span></div>
      <div className="hero-main"><h1>GOOD AIR.<br /><span>STEADY HANDS.</span></h1><div className="hero-dial"><AirDial /><span className="dial-foot">THE RIGHT FIX. THE RIGHT REASON.</span></div></div>
      <div className="hero-bottom"><p>A home that feels right.<br />A crew that explains why.<br /><span>Heating, cooling, and no guesswork.</span></p><div className="hero-paths"><div><Action href="#call">Repair call demo</Action><span className="path-caption">THE SOMETHING’S-NOT-RIGHT ROUTE</span></div><div><Action href="#request" variant="outline">Plan a new system</Action><span className="path-caption">THE LET’S-THINK-IT-THROUGH ROUTE</span></div></div></div>
      <div className="hero-footnote"><span><i className="status-dot" />CONCEPT SERVICE AREA: COLUMBUS & NEARBY</span><span>ILLUSTRATIVE HOURS: {site.hours.toUpperCase()}</span><a href="/crew#service-area">Explore the area <Arrow /></a></div>
    </section>
    <div className="home-photo"><Photo priority /><div className="image-margin-note"><span>01 — THE STEADY APPROACH</span><span>LOOK CLOSELY. EXPLAIN CLEARLY. DO IT PROPERLY.</span></div></div>
    <section className="service-section page-gutter section-space" data-reveal>
      <SectionIntro number="01" label="A CLEAR WAY FORWARD" title={<>Different needs.<br />Same steady approach.</>} description="A repair shouldn’t become a sales pitch. A new system shouldn’t begin with a guess. Start with what your home actually needs." />
      <div className="service-path-grid"><Link href="/repairs" className="service-path"><span className="service-number">01 / REPAIR</span><div className="service-symbol" aria-hidden="true">↗</div><h3>Let’s find<br />what’s wrong.</h3><p>No cooling. Uneven heat. A noise that’s new. Start with a careful diagnosis and an explanation you can use.</p><span className="service-link">Heating & cooling repairs <Arrow /></span></Link><Link href="/new-systems" className="service-path service-path-lime"><span className="service-number">02 / REPLACE</span><div className="service-symbol"><Mark /></div><h3>Let’s plan<br />what’s next.</h3><p>A system that fits the house and the way you live. Understand the options before making the decision.</p><span className="service-link">Explore a new system <Arrow /></span></Link></div>
      <div className="maintenance-line"><span className="eyebrow">ALREADY RUNNING WELL?</span><p>A little attention can help keep it that way.</p><Link href="/repairs#maintenance" className="text-link">Talk maintenance <Arrow /></Link></div>
    </section>
    <section className="standards-section page-gutter section-space" data-reveal><div><Eyebrow light>02 / NO MYSTERY IN THE WORK</Eyebrow><h2>The explanation<br />is part of<br /><em>the repair.</em></h2><p>You shouldn’t need to speak HVAC to make a good decision about your home.</p><Link className="text-link" href="/crew">How this crew would work <Arrow /></Link></div><div className="standards-list">{[{ title: "Find the cause.", body: "Listen to what changed. Look at the whole system. Explain what the checks show before recommending a fix." }, { title: "Make the options clear.", body: "What needs attention now, what can wait, and what each option involves. Agree on the scope before work starts." }, { title: "Leave it better.", body: "Protect the floor. Keep the work area tidy. Walk through the finished work and leave understandable notes." }].map((item, i) => <div key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.body}</p></div>)}</div></section>
    <section className="crew-teaser page-gutter section-space" data-reveal><Eyebrow>03 / PEOPLE, NOT A CALL CENTER</Eyebrow><div className="crew-teaser-content"><h2>A small crew.<br />A name behind<br />the work.</h2><div><Photo className="crew-teaser-photo" src="/images/steady-crew.webp" alt="Four fictional HVAC crew members standing beside an unbranded white service van in a residential driveway." captionText="AI-GENERATED FICTIONAL CREW · NOT REAL EMPLOYEES" /><p className="large-copy">Steady is imagined as an owner-led team of four. The person explaining the job knows the person doing it.</p><p>That means useful handoffs, care around your home, and someone who can explain the recommendation without reaching for a script.</p><p className="small-note">An illustrative crew model, not real employee profiles.</p><Link href="/crew" className="text-link">Get to know the Steady approach <Arrow /></Link></div></div></section>
    <section className="work-examples page-gutter section-space" data-reveal><SectionIntro number="04" label="WHAT THOUGHTFUL WORK LOOKS LIKE" title={<>Behind every system,<br />there’s a house to understand.</>} /><div className="example-grid"><article><span className="eyebrow">ILLUSTRATIVE SCENARIO / 01</span><h3>The upstairs<br />that never cools.</h3><p>Before suggesting a larger unit, an assessment considers airflow, insulation, sun exposure, and how the existing system serves each floor.</p><Link className="text-link" href="/field-notes/repair-or-replace">See what an assessment covers <Arrow /></Link></article><article><span className="eyebrow">ILLUSTRATIVE SCENARIO / 02</span><h3>The furnace with<br />one more repair.</h3><p>A useful conversation weighs the fault, equipment condition, repair history, and your plans for the home. Age alone doesn’t make the decision.</p><Link className="text-link" href="/new-systems">Understand your options <Arrow /></Link></article></div><p className="small-note">Example situations only. These are not completed projects or claims about results.</p></section>
    <section className="callback-section page-gutter section-space" data-reveal><div><Eyebrow>05 / A BETTER FIRST CONVERSATION</Eyebrow><h2>Less back-and-forth.<br />More getting somewhere.</h2><p>Tell us a little about your home and what you’re considering. The callback can start with context, instead of starting from scratch.</p><Action href="#request">Try the assessment preview</Action><p className="small-note">Local demo of Adrocity Lead Qualifier. Nothing is submitted.</p></div><div className="callback-ticket"><div className="ticket-top"><Mark /><span>A GOOD START<br />TO A USEFUL CALL</span></div><ol><li><span>01</span><div><h3>Your home.</h3><p>The area and the system you have.</p></div></li><li><span>02</span><div><h3>Your priorities.</h3><p>What’s changed. What you want to improve.</p></div></li><li><span>03</span><div><h3>Your next step.</h3><p>A prepared conversation, not an automatic booking.</p></div></li></ol><span className="ticket-bottom">THOUGHTFUL QUESTIONS → A CLEARER HANDOFF</span></div></section>
    <section className="area-section page-gutter section-space" data-reveal><ServiceAreaGraphic /><AreaDetails /></section>
    <section className="journal-feature page-gutter section-space" data-reveal><div className="journal-heading"><SectionIntro number="06" label="FIELD NOTES" title={<>A little know-how.<br />A better decision.</>} /><Link href="/field-notes" className="text-link">All field notes <Arrow /></Link></div><div className="journal-grid">{articles.map((article, i) => <Link key={article.slug} href={`/field-notes/${article.slug}`} className="journal-card"><div className={`journal-art journal-art-${i}`} aria-hidden="true">{i === 0 ? <><span>REPAIR</span><span className="art-vs">OR</span><span>REPLACE?</span></> : <><span className="air-line" /><span>LESS COOL?</span><span>MORE CONTEXT.</span><Mark /></>}</div><div className="journal-card-meta"><span>FIELD NOTE / 0{i + 1}</span><span>{article.readTime}</span></div><h3>{article.title}<Arrow diagonal /></h3></Link>)}</div></section>
    <ClosingCTA />
  </>;
}

