import Image from "next/image";
import Link from "next/link";
import { Arrow, Mark, RouteLine } from "./graphics";
import { site } from "@/lib/site";

export function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`eyebrow ${light ? "eyebrow-light" : ""}`}><span className="tiny-cross" aria-hidden="true">+</span>{children}</p>; }
export function Action({ href, children, variant = "dark" }: { href: string; children: React.ReactNode; variant?: "dark" | "lime" | "outline" }) { return href.startsWith("#") ? <a className={`button button-${variant}`} href={href}>{children}<Arrow diagonal /></a> : <Link className={`button button-${variant}`} href={href}>{children}<Arrow diagonal /></Link>; }
export function SectionIntro({ number, label, title, description }: { number: string; label: string; title: React.ReactNode; description?: string }) { return <div className="section-intro"><Eyebrow>{number} / {label}</Eyebrow><h2>{title}</h2>{description && <p className="section-description">{description}</p>}</div>; }
export function Photo({ className = "", priority = false, caption = true, src = "/images/steady-fieldwork.webp", alt = "Illustrative scene of a technician beside a closed outdoor air conditioner at a tree-lined home.", captionText = "AI-GENERATED CONCEPT IMAGE · NOT AN ACTUAL CREW OR JOB" }: { className?: string; priority?: boolean; caption?: boolean; src?: string; alt?: string; captionText?: string }) { return <figure className={`documentary ${className}`}><div className="photo-wrap"><Image src={src} alt={alt} fill sizes="(max-width: 700px) 100vw, (max-width: 1200px) 60vw, 90vw" priority={priority} className="field-photo" /><span className="photo-stamp" aria-hidden="true"><Mark />STEADY<br />IN THE FIELD</span></div>{caption && <figcaption><span>FIELD IMAGE / ILLUSTRATIVE SCENE</span><span>{captionText}</span></figcaption>}</figure>; }
export function ClosingCTA({ title = <>Let’s get your home<br />feeling right.</> }: { title?: React.ReactNode }) { return <section className="closing-cta"><div><Eyebrow>ONE CLEAR NEXT STEP</Eyebrow><h2>{title}</h2></div><div className="closing-actions"><Action href="#request">Request a system assessment</Action><a className="text-link" href="#call">Something stopped working? Try the call demo <Arrow /></a><p>Fictional company. Explore the experience; nothing is sent.</p></div><RouteLine /></section>; }
export function AreaDetails() { return <div className="area-details"><Eyebrow>COLUMBUS, OHIO & THE NEIGHBORHOODS AROUND IT</Eyebrow><h2>Close to home.<br />Accountable for it.</h2><p>From older homes with a few quirks to newer builds with rooms that never feel quite right. A small crew, working close to home.</p><div className="neighborhood-list">{site.areas.map(area => <span key={area}>{area}<span aria-hidden="true">↗</span></span>)}</div><p className="small-note">Illustrative service area and hours: {site.hours}. Steady is not an operating contractor.</p><Link className="text-link" href="/crew">Meet the idea behind the crew <Arrow /></Link></div>; }
